task: 'if_nerf'
gpus: [0]

parent_cfg: 'configs/snapshot_exp/snapshot_f3c.yaml'

train_dataset:
    data_root: '../EasyMocap/data/1v1p_keypoint_test/1v1p'
    human: 'custom'
    ann_file: '../EasyMocap/data/1v1p_keypoint_test/1v1p/annots.npy'
    split: 'train'

test_dataset:
    data_root: '../EasyMocap/data/1v1p_keypoint_test/1v1p'
    human: 'custom'
    ann_file: '../EasyMocap/data/1v1p_keypoint_test/1v1p/annots.npy'
    split: 'test'

# data options
ratio: 1.
training_view: [0, 6, 12, 18]
num_train_frame: 300
smpl: 'smpl'
vertices: 'vertices'
params: 'params'
big_box: True
